### ISSUE TITLE
Show undo message in place of deleted item

### ISSUE THREAD

**Issue by timroes** [timroes/EnhancedListView#1]
Show the undo message in place of the deleted list item, instead as a window popup (Gmail style).

**Comment by NathofGod** [comment]
I'm really itching for this. Has any work begun?

**Comment by timroes** [comment]
Hi. I am currently not working on that and it has a low priority on my list. 0.3.0 will contain some improvements and configuration options, and 0.4.0 will mainly be orderable listitems. And I don't even know when I will find time for these.

**Comment by hamen** [comment]
+1

**Comment by aaronennis5778** [comment]
+1

**Comment by timroes** [comment]
Won't fix on this library anymore. Please see deprecation notice in the README file.
