### ISSUE TITLE
Applications that use appcompat fail due to the theme not being a descendant of appcompat

### ISSUE THREAD

**Issue by amenon** [timroes/EnhancedListView#12]
Is there is a need for a theme in the library? Removing that from styles.xml in values-v11 should fix this.

**Comment by timroes** [comment]
Of course there is no need. It's a left over of the default project structure created by the sdk. Sorry for that. I will remove it, and push a new version.

**Comment by timroes** [comment]
Published a new version. Will be available within the next 2 hours via maven central. Thanks for your report!

**Comment by amenon** [comment]
Thanks for the quick turnaround. Awesome library btw!
