### ISSUE TITLE
Maven Dependency Problem

### ISSUE THREAD

**Issue by syr** [timroes/EnhancedListView#13]
just wanted to try EnhancedListView.by putting it to a android quickstart maven project (generated by: mvn archetype:generate  -> 123)
Added the maven EnhancedListView dependency in the pom 

```
    <dependency>
        <groupId>de.timroes.android</groupId>
        <artifactId>EnhancedListView</artifactId>
        <version>0.1.2</version>
    </dependency>
```

but idea 12 marks com.android.support:support-v4:13.0.0 red because it cannot find it.

Any idea for a bloody beginner, please :-)

P.S. here the pom: http://pastebin.com/fL0PyrvM

**Comment by timroes** [comment]
You might need to install the Google Repositories from the Android SDK Manager. For whatever reason Google doesn't sync its stuff to Maven Central, so this dependency cannot be resolved if you are missing their repositories.

**Comment by syr** [comment]
Thanks for the reply. Installed support libs and google apis.
Because it didn't changed a thing i copied everything in androidsdk\sdk\extras\android\m2repository\
to my maven repo and did reimport maven dependcies.

Only thing that changed is that the dependencies of de.timroes.android:EnhancedListView:0.1.2 is no more red marked but your lib itself.

Tried a mvn clean install and get as expected:

Could not resolve dependencies for project .....:apk:1.0-SNAPSHOT: Could not find artifact de.timroes.android:EnhancedListView:jar:0.1.2 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by timroes** [comment]
That might be, because you are missing the type in the dependency. There is no non-official old 'apk' library in maven central, only an Android Archive (aar). So you have to add <type>aar</type> to your dependency tag. But.. I don't know if the maven android stuff does support AAR files already. It might be, that it won't work, because the maven plugin doesn't support this format.

**Comment by syr** [comment]
Anyone who got the same android maven dependency problem should use "maven android sdk deployer" (https://github.com/mosabua/maven-android-sdk-deployer). It copies the android libs to the local maven repo.

Whereas it didn't solve the dependency problem with the enhanced list view itself, I had to use the swipe2dismiss-implementation of  Roman Nurik which worked but doesn't come with an undo feature: http://code.google.com/p/dashclock/source/browse/main/src/com/google/android/apps/dashclock/ui/SwipeDismissListViewTouchListener.java?r=a7968ff883ad627869130ec6ec7c31554ca9954b
