### ISSUE TITLE
Merging EnhancedListView and your ABSListView.

### ISSUE THREAD

**Issue by arichiardi** [timroes/EnhancedListView#20]
Hi Tim! First of all good job ;)
Secondly, would it make sense to merge this EnhancedListView with the ABSListView you have in android-snippets? The one for enabling Sherlock ActionBar features?
Thanks and keep it up :+1: !

**Comment by timroes** [comment]
Hi,

unfortunately I won't merge these. With ActionBarCompat there exists an widespread alternative to ABS, so I wouldn't want to make the lib specific to one of these support libs. Also the share of > API 11 devices (which support this feature natively) is increasing constantly. So I would like to use the time I work on this project to implement new features (not provided by newer API levels) and fixing bugs and leave the multiselect backward compatibility to the using developer, who also knows what backward compatibility lib she uses.

Sorry for that negative answer :-(
