### ISSUE TITLE
Change text button "Undo"

### ISSUE THREAD

**Issue by joselufo** [timroes/EnhancedListView#23]
Is it possible to change the text to the undo button?

**Comment by timroes** [comment]
You can override (or internationalize) the strings by putting string resources in your own resource files with the same name. You can find the names here:

https://github.com/timroes/EnhancedListView/blob/master/EnhancedListView/src/main/res/values/strings.xml

So just put a `<string name="undo">...</string>` to your resources.

**Comment by timroes** [comment]
If this solved your problem please close the issue, otherwise drop another message, I will see if I can help you :)
