### ISSUE TITLE
Change location of Toast message

### ISSUE THREAD

**Issue by saadfarooq** [timroes/EnhancedListView#25]
I need to change the location of the toast since it overlaps a button in my UI. Is there any exposed interface to do this ?

A simple margin should be enough but I couldn't find anything in the resources that could help.

**Comment by timroes** [comment]
Unfortunately there is no method right now. I will mark that for the next release, unfortunately I cannot guarantee that it will be in time for you. Until I released another version my recommendation would be to include the library by source code in your own project and change the appropriate lines ( https://github.com/timroes/EnhancedListView/blob/master/EnhancedListView/src/main/java/de/timroes/android/listview/EnhancedListView.java#L830 ) yourself. If you don't make any other large modifications you can easily change back to a maven version once this feature has been released.

**Comment by saadfarooq** [comment]
Thanks. I sent a pull request with the update. I can use a local maven install for now until your next release. We can discuss if that particular solution is amenable on that PR thread. 
Cheers.

**Comment by timroes** [comment]
Adding resource files isn't like adding api for me, so it can go with a patch and doesn't need a minor update ;) I will see that I merge it within the next .. let's say 3 .. days.

**Comment by saadfarooq** [comment]
Thanks

**Comment by timroes** [comment]
So much for 3 days ... Fixed in 0.3.1 - I somehow forgot it in 0.3.0 that's why these two close releases. And yeah I know it's not really semantic versioning that way, but without the 1 in the front, we are anyway not stable ;)
