### ISSUE TITLE
mSlop for horizontal swipe is too low

### ISSUE THREAD

**Issue by moogoat** [timroes/EnhancedListView#29]
When using the view with swipe to dismiss on, repeated vertical scrolling often gets interrupted by the initiation of a swipe action (try making a long list, and scrolling as fast as you can to the bottom). I think this is because mSlop is set too low.

I know the documentation says you should use vc.getScaledTouchSlop(), but I think this is far too low in this context. I've had pretty better results with a constant value of 48dp:

`mSlop = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 48, ctx.getResources().getDisplayMetrics());`

**Comment by timroes** [comment]
I will leave the vc.getScaledTouchSlop() as a default, but will make it configurable in the next release.
