### ISSUE TITLE
WindowLeak Exception + Solution in pull request

### ISSUE THREAD

**Issue by ranhaveshush** [timroes/EnhancedListView#31]
WindowLeak Exception when invoking mUndoPopup.dismiss(); while the container window is no longer visible.

Scenario:
1. Swipe to dismiss so reveal the undo popup window.
2. Press the Home button to go to the recently used apps view.
3. Swipe to dismiss the application.

Now if you set the EnhancedListView to:
myEnhancedListView.setRequireTouchBeforeDismiss(true);

You'll get an exception of WindowLeak on the undo popup window which didn't had the time to dismiss himself.

Or worse if you set the EnhacedListView to:
myEnhancedListView.setRequireTouchBeforeDismiss(false);
myEnhancedListView.setUndoHideDelay(10000);   (10 sec so you have time to dismiss the application).

The application will crush cos the undo popup window which will try to dismiss himself after 10 seconds but the container layout is no longer exists.

**Comment by timroes** [comment]
Fixed in v0.3.0
