### ISSUE TITLE
listview refresh bug

### ISSUE THREAD

**Issue by xalexchen** [timroes/EnhancedListView#4]
hey,first great work,cool stuff.
i try to build this demo this morning.i found a little bug in listview refresh.when i swipe to dismiss item.sometime it will appear the following bugs (black line)
![device-2013-09-24-104337](https://f.cloud.github.com/assets/1987963/1196981/ba2b8234-24c3-11e3-9975-e1cf7a19d1ca.png)

on this moments when i try to Reset items than
![device-2013-09-24-104352](https://f.cloud.github.com/assets/1987963/1196982/caf3ab46-24c3-11e3-9962-4da1ed695dfb.png)

any idea ?

**Comment by timroes** [comment]
Hei I will have a look at that today evening. Could you tell me if you swiped in a special way (order of the items you swiped, speed you swiped)? Anything that could help me to reproduce that bug :)

**Comment by xalexchen** [comment]
i think the speed issue.when i swipe one item to dismiss , do not wait black line dismiss(or maybe wait until the request layout animation finished),then continue to swipe the near by item.(yes,it must be near by item) then the things happen.

xalexchen

From: Tim Roes
Date: 2013-09-24 16:58
To: timroes/EnhancedListView
CC: Alex.Chen
Subject: Re: [EnhancedListView] listview refresh bug (#4)
Hei I will have a look at that today evening. Could you tell me if you swiped in a special way (order of the items you swiped, speed you swiped)? Anything that could help me to reproduce that bug :)

**Comment by timroes** [comment]
I was able to reproduce this on an old 2.3 device. So I will have a look at it soon. But at least it doesn't appear on 'modern' devices ;)

**Comment by timroes** [comment]
Found it :) .. And my fingers hurt from fast swiping ;)
Will try to find the other bug today evening, and push a fixed update tomorrow (together with a new demo app).

**Comment by xalexchen** [comment]
：）good

**Comment by ghost** [comment]
Hi Tim, 

This is a nice library,  and great work . I have included  it in one of our key project as maven dependency and still experience this bug when randomly swiping very fast on the EnhancedListView. "06-10 09:49:48.929: E/AndroidRuntime(29631): java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1".  

Do you have an idea of what might  be the cause of the problem?

**Comment by timroes** [comment]
@klaaskabini The bug unfortunately still exists. The new bug report ist #7 .
I haven't been able to track it down yet, and would be very happy if anyone has any ideas, what is causing this.
