### ISSUE TITLE
New GMail like design

### ISSUE THREAD

**Issue by tprochazka** [timroes/EnhancedListView#45]
Do you have in plan to add design like new gmail app use?
I mean inline undo button instead off Toast like design.

**Comment by timroes** [comment]
Hi, there is already an issue here: 

https://github.com/timroes/EnhancedListView/issues/1

Unfortunately I am currently not having much spare time, so I won't count on the feature within the next month :-/ Also it doesn't have the highest priority on my list (would rather like to implement drag'n'drop reordering of the list first).

**Comment by timroes** [comment]
Won't fix on this library anymore. Please see deprecation notice in the README file.
