### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by akohout** [timroes/EnhancedListView#46]
I can't find a license under which you publish this library.. What's your idea here?

**Comment by MarcoLizza** [comment]
As far as I can tell, Apache License Version 2.0 (see https://github.com/timroes/EnhancedListView/wiki)...

**Comment by akohout** [comment]
Ah ok, I didn't look at the wiki :-) Maybe it's a good idea to provide a LICENSE file at the root of the repository.
