### ISSUE TITLE
Android 5.0 Undo message appearing on top of Navigationbar.

### ISSUE THREAD

**Issue by DanielMartinus** [timroes/EnhancedListView#59]
The Undo bar is appearing on top of the navigation bar in Android 5.0 or higher.
When i set the dimens of the undo bar according to the docs it will also appear higher on devices lower than Android 5.0. It should be possible to set the dimens during runtime or fix the bug for Material 5.0.

**Comment by ClementHard** [comment]
You can create a values-v21 resource folder containing a dimens.xml file overriding the bottom offset value.

res/values-v21/dimens.xml

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <dimen name="elv_undo_bottom_offset">63dp</dimen> <!-- 48dp + 15dp -->
</resources>
```
