### ISSUE TITLE
Whole list dismissed after swipe.

### ISSUE THREAD

**Issue by hsanson** [timroes/EnhancedListView#8]
I tried to use this EnhancedListView but every time I swipe one item the whole list dissapears. I am not sure if is that all items are deleted from the list or the list itself is removed from the layout. I have to refresh the cursor loader for the items to appear again but this causes a irritating flickering after each dismiss.

The only different thing from the demo app is that my list lies on top of a sliding up panel: https://github.com/umano/AndroidSlidingUpPanel.git.

**Comment by timroes** [comment]
Thanks for your report. I will try to reproduce this today evening. It might be, that the two libs doesn't work together, if they conflict in the touch event handling. If that's the problem, I will try to find a workaround for that.

**Comment by timroes** [comment]
Unfortunately I wasn't able to reproduce it. If I put a EnhancedListView inside the slider, it doesn't vanish (or any unexpected items are deleted). If you would like me to have a look at it, you could send me your project to mail@timroes.de. If you don't want (or are allowed to), at least the layout XML would be nice (thought I am not sure, it will be enough to find the problem).

**Comment by hsanson** [comment]
Please ignore me... I was closing the cursor of my CursorAdapter after removing the item from the list. I fixed it and got your EnhancedListView working nicely in my application.

Thanks...
